### ISSUE TITLE
As a Seacom developer I want to have two virtual machine so that I can install Elasticsearch and develop the IIS log file analyzer

### ISSUE THREAD

**Issue by ohnewein** [idm-suedtirol/big-data-for-tourism#1]
- [x] setup ubuntu machine
- [x] setup security group to give ssh admin access to  access to seacom
- [x] create account/s for seacom as soon as ssh public keys have been provided

**Comment by bertolla** [comment]
Hi guys,
I'll need a(at least one) public ssh key for the user Seacom needs.
I already requested it a while ago but didn't get any.
@sseppi Can you remind them please

**Comment by sseppi** [comment]
I requested the ssh public key to Seacom, They where on holyday in this weeks, so I hope that they will send it to us as soon asp possible.

**Comment by bertolla** [comment]
finished setups. ec2 instances are little bit expensive and do not equivalate to what requested for the simple reason that ec2 instances have fixed specs(RAM and CPU's). I would let them use it as it is and if they really need more cpus we still can go up.
@sseppi When will they start using the machines? As soon as they are ready to use them i will start 'em.

**Comment by puecher** [comment]
Hi there:
- does the virtual machine replace the current Elastic Cloud instance?
- do we use IIS instead of Tomcat?
Thanks for the info.

**Comment by sseppi** [comment]
Hi @puecher ,
no your code will run in the current Elastic Cloud instance.
This two machines are for another Work Package of the project Big Data 4Tourism.
We will make an internal test of a dashboard that makes some statistics about IIS log files.
Did I answer to your question?
THX
Stefano

**Comment by puecher** [comment]
Great, thanks for the info Stefano ;)

**Comment by ohnewein** [comment]
There are now 3 virtual machines and are running.
