### ISSUE TITLE
As a DAVINCI PM I want the Big Data 4 Tourism scoreboard online, in order to be able to analyze tourism reservation data.

### ISSUE THREAD

**Issue by sseppi** [idm-suedtirol/big-data-for-tourism#20]
Deadline: 16th of December 2019

- [x] Move old Kibana public dashboard previously on https://bigdata4tourism.davinci.bz.it to https://kibanapublic.bigdata4tourism.davinci.bz.it
- [x] Point https://bigdata4tourism.davinci.bz.it to the new scoreboard

**Comment by Piiit** [comment]
@sseppi @ohnewein Done. Please test on https://bigdata4tourism.davinci.testingmachine.eu/

Should I put this also to production (https://bigdata4tourism.davinci.bz.it)?

**Comment by ohnewein** [comment]
@Piiit looks great!

Not sure what happens to the Kibana UI, if we go to production. At the moment on production, there is the Kibana UI. Will that be moved to a different URI?

**Comment by Piiit** [comment]
Wrote an email to Alex, Stefano, Patrick O. and Ulrich to ask what to do
