### ISSUE TITLE
As a BigData4Tourism I want to have the uploader online in order to be able to upload the data in the new Elastich Search infrastructure.

### ISSUE THREAD

**Issue by sseppi** [idm-suedtirol/big-data-for-tourism#5]
- Uli Seppi is testing and improving it. Deadline: July 1st

**Comment by bertolla** [comment]
ready to be tested on http://upload.bigdata4tourism.testingmachine.eu

**Comment by bertolla** [comment]
We tested it during the confcall and we noticed that the upload did not work correctly. The ftp access is not working properly. I noticed on the testeserver that the ftp credentials are missconfigured.
 P.Moser did they same thing with the airquality datacollector, see https://github.com/idm-suedtirol/bdp-commons/blob/master/data-collectors/airquality-appabz/Jenkinsfile-Production.
Maybe we could do it the same way.

**Comment by alexlanz** [comment]
The problem should now be fixed! We will test it more when also Apache Nifi and Kibana is ready.

**Comment by ohnewein** [comment]
Uli Seppi is testing it

**Comment by RudiThoeni** [comment]
what is the year of the deadline?

**Comment by sseppi** [comment]
@RudiThoeni  we are finally online! The year seems to be 2019 ;-).

Now the BigData4Tourism are online under the following link:
-  https://upload.bigdata4tourism.davinci.bz.it
-  https://bigdata4tourism.davinci.bz.it
-  https://kibana.bigdata4tourism.davinci.bz.it
